KM_variance_estimator
sebp/scikit-survival pull request #320
Opened 2022-11-04 21:11 UTC by TristanFauvel

**Checklist**

- [x] py.test passes
- [x] tests are included
- [x] code is well formatted
- [ ] documentation renders correctly

**What does this implement/fix? Explain your changes**

Hi @sebp,
I added the Greenwood's estimation of KM variance to nonparametric.py (this is a prerequesite for implementing some goodness-of-fit tests).
NB:  I ran tox -e py310-docs but for some reason the new function does not not appear in the API. 
Best,

2022-11-12 19:24 UTC, sebp requested changes
Thanks for your PR!

Could you please revert the code style changes and `prod.txt` so it is easier to see the relevant changes.

Moreover, some of your code is not covered by tests. I'd appreciate if you could provide tests that cover all your code.

2022-11-22 21:00 UTC, sebp requested changes
Thanks for updating the code.

Currently, there's a lot of duplicate code shared with `kaplan_meier_estimator`. Therefore, I would suggest to add the code for variance estimation to `kaplan_meier_estimator`.

2022-12-05 20:34 UTC, TristanFauvel commented on sksurv/nonparametric.py
> +        where=(n_events != 0) & (n_at_risk != n_events),
In TestKaplanMeier, test_simple for data_all_uncensored includes the scenario where `n_at_risk == n_events`.

2022-12-18 19:58 UTC, sebp commented
@TristanFauvel Could you please rebase on latest master, which fixes a couple of issues with CI.

2022-12-31 17:49 UTC, sebp commented
FYI, your changes look good. Thanks so much for contributing 🤩

Since variance isn't all that useful on its own, I'm planning to a add support for confidence intervals based on your code.

2023-04-02 10:14 UTC, closed without merging