Added conditional property to expose time scale predictions
sebp/scikit-survival pull request #327
Opened 2022-12-09 13:37 UTC by Finesim97

**Checklist**

- [X] closes #324 
- [X] py.test passes
- [ ] tests are included
- [X] code is well formatted
- [X] documentation renders correctly

Added a decorator for properties, which are only available, if a check returns true. The decorator provided by scikit-learn only works for functions sadly.

@sebp 
I am not sure what to test exactly, maybe a test which tests whether pipelines correctly patch the property and functions through? I also think this should not show up in the documentation, as it is internal?

2022-12-09 13:43 UTC, Finesim97 commented
Fixed the Codacy issue.

2022-12-18 19:58 UTC, sebp commented
@Finesim97  Could you please rebase upon latest master, which fixes a couple of issues with CI.

2023-01-02 10:09 UTC, Finesim97 commented
Happy new year to you! Rebased it.

2023-01-02 18:02 UTC, Finesim97 commented
Imports wrongly sorted, will fix it

2023-02-26 12:29 UTC, sebp commented
@Finesim97 Do you plan to continue working on this?

2023-03-01 19:15 UTC, Finesim97 commented
Hi, 
The server I used to work on this went up in flames and I started my new job, but I will fix this over the following days!

2023-03-03 11:40 UTC, Finesim97 commented
Sry, I ran the wrong command and screwed up my commits, fixing it at the moment

2023-03-03 12:11 UTC, Finesim97 commented
Because it is implemented with a `@property`, the mechanism from scikit-learn did not work (it only supports functions), instead I added a @property with support for conditional checks.

2023-03-04 06:13 UTC, Finesim97 commented
I will add some tests to fix codecov

2023-04-11 08:34 UTC, Finesim97 commented
Hi, I added a test for the conditional property.

2023-05-15 10:59 UTC, Finesim97 commented
Sorry that everything took so long, but I think now the PR should be ready!

2023-05-16 16:27 UTC, sebp requested changes
Thanks for your effort. Looks good, except for some small changes.

2023-05-16 16:27 UTC, sebp commented on sksurv/util.py
> +            f"This {repr(obj)} has no attribute {repr(self._name)}"
Instead of `{repr(obj)}`, you can use `{obj!r}`, and move the definition of `attr_err` into the if block.

2023-05-16 16:27 UTC, sebp commented on sksurv/util.py
> +class _ConditionalAvailableProperty:
I wonder if you could inherit from the built-in `property`, because it is a class. This could allow removing the setter/getter/deleter code.

2023-06-10 15:44 UTC, sebp commented
@Finesim97 Thanks for your contributions. PR #374 is base on your work. This PR is now obsolete.

2023-06-10 15:44 UTC, closed without merging