Cumulative Incidence (Kaplan-Meier) for competing risks.
sebp/scikit-survival pull request #491
Opened 2024-11-05 10:49 UTC by mvlvrd

Add non-parametric Cumulative Incidence (Kaplan-Meier) for competing risks. Tests included.

**Checklist**

- [ x] closes #490
- [ x] pytest passes
- [ x] tests are included
- [ x] code is well formatted
- [ x] documentation renders correctly

**What does this implement/fix? Explain your changes**
Implements cumulative incidence estimator for the competing risks case. Confidence Intervals are not implemented but are under development.

2024-11-07 05:46 UTC, mvlvrd commented
The codacy linter triggers for unused unpacked assignments, however the ruff linter doesn't. Perhaps it would be nice to make them consistent, though is not a big issue. (I can open a new issue/PR if needed, it is trivial to fix it from the ruff side).

2024-11-10 10:03 UTC, sebp requested changes
This is great, thanks a lot!

The code seems to be correct to me. I would suggest to improve the API docs a little bit to avoid ambiguities.

In addition, I'm not sure if certain corner cases are covered. For instance, what happens if no event has been observed for one (or more) competing risk?

I would appreciate if a test case with more than 2 competing risks could be added.

2024-11-15 10:43 UTC, mvlvrd commented
Thanks so much for the review!
I think I have addressed most of your points. I have been looking for a real dataset with more than two risks, but I couldn't find one, so I added a simulated one. Corner cases like zero events for one (or more) particular risk are not included and raise an error.

I also changed the function name (removing the reference to Kaplan-Meier). This is because I found a couple of papers that use KM for the naive extension of KM to the competing risks case, while we are using the rigorous estimator that does not assume independence between risks.

2024-11-23 13:30 UTC, sebp commented on sksurv/nonparametric.py
> +    >>> plt.show()
CSV if fine. Can you please add an entry to https://github.com/sebp/scikit-survival/blob/master/sksurv/datasets/data/README.md describing the dataset with a link to its source. Adding a function to load the dataset to `sksurv.datasets` would be great.

2024-11-26 18:16 UTC, sebp requested changes

2024-11-26 18:16 UTC, sebp commented on tests/data/bmt.csv
Can you please remove this file and use sksurv.datasets.load_bmt instead

2024-11-27 19:09 UTC, sebp approved these changes

2024-11-27 19:10 UTC, merged