Add confidence intervals to the cumulative incidence estimator for competing risks.
sebp/scikit-survival pull request #500
Opened 2024-12-06 05:41 UTC by mvlvrd

There are some minimal differences in the results of the confidence intervals with respect to the implementation in
the R package cmprsk, so we add some tolerance to the assertions. Apart from the Aalen estimator used in cmprsk we include two other estimators, but these are not tested so thoroughly, because we couldn't find implementations.

There is a new data set with three different terminal states.

**Checklist**

- [ ] closes #xxxx
- [x] pytest passes
- [x] tests are included
- [x] code is well formatted
- [x] documentation renders correctly

**What does this implement/fix? Explain your changes**

2024-12-17 02:19 UTC, mvlvrd commented
Thanks for the reply!
- Aalen estimator is based on counting process theory and it is tested against the `cmprsk` R package, implemented by Gray. The actual formula used is Eq. 4.5 from Pintilie's book.
- Dinse comes from the Delta method applied to the cumulative incidence estimator, assumed it follows a multinomial distribution. I couldn't find any external implementation, so the test data is the data generated by the current code. The formula used is derived from the original Dinse-Larson paper.
- Dinse_approx is a large number of events approximation of the Dinse estimator. It seems that the approximation was popular in the  00's but with current computing power I guess it is not relevant anymore. Nevertheless, I have included it because I couldn't find real data to test the "full" Dinse estimator. The formulas used are derived from Dinse and Larson original paper and are equivalent to Eq. 4.4 in Pintilie's book.
 
There are multiple versions of both kind of estimators. According to Braun and Yuan (Statist. Med. 2007; 26:1170–1180), the Dinse-based estimators seems to work better than the Gray version of the Aalen-based estimator and "are fairly accurate even in small samples". I have decided to include both kind of estimators for completeness and because the Aalen estimators seem to be the standard due to the R implementation.

Apart from this, I have the personal impression that the Aalen-based estimators would not work properly in the case of discrete time because of the possibility of multiple simultaneous events. But I don't understand the theory well enough to justify it.

So in practice, I think Dinse is the best practical solution, while Aalen would be useful when comparing with the `cmprsk`  implementation. Dinse_approx could be deprecated, but may be useful for historical reasons.

I am sorry if this is confusing, I am not an expert on these issues and it took me a while to go through the literature and such.

BR,

2024-12-21 12:47 UTC, mvlvrd commented
I tried to back-engineer the `cmprsk` code and I think it may be not the same formula. I plotted all three components for both the Fortran code (`va`, `vb` and `vc`) and our implementation (`var_a`, `var_b` and `var_c`) and they are quite different from each other, but somehow the differences cancel out.


Regarding the Dinse formula, I think (B1) in Choudhury (2002) is wrong: 
                   
$$ \prod_{l=1}^{r-1} \frac{c_{(l)}}{N_l(N_l - c_{(l)})} $$

should be
                          
$$ \prod_{l=1}^{r-1} \left( 1 + \frac{c_{(l)}}{N_l(N_l - c_{(l)})} \right) $$

The right formula can be deduced from [Dinse et al. (1986)](https://www.researchgate.net/profile/Gregg-Dinse/publication/243082882_A_Note_on_Semi-Markov_Models_for_Partially_Censored_Data/links/57e0887908ae3f2d793eb293/A-Note-on-Semi-Markov-Models-for-Partially-Censored-Data.pdf?_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6InB1YmxpY2F0aW9uIiwicGFnZSI6InB1YmxpY2F0aW9uIn19) Eq. 5  
I actually first tried to implement it using the formula in Choudhury's paper, but got very bad results. Then I went to the original Dinse's paper and noticed the error. Notice how the Taylor expansion doesn't work if you use the wrong formula.

Regarding the missing `axis` argument, I think it is not needed, because `x` only has one index (the time variable `l`) and no dependence on the type of risk.

I attach the relevant part of Pintilie's book
[pintilie_var.pdf](https://github.com/user-attachments/files/18217755/pintilie_var.pdf)

2024-12-31 12:57 UTC, sebp requested changes
I apologize for the delay.

I don't have any major concerns. The code seems to be correct, although I did not compare against reference implementation yet. 

I'm not sure what exactly R's cmprsk implements. mstate seems to implement the Aalen estimator. So far, I could not find an R implementation of the Dinse estimator. Only [STATA](https://journals.sagepub.com/doi/10.1177/1536867X0400400201) and [SAS](https://support.sas.com/documentation/cdl/en/statug/68162/HTML/default/viewer.htm#statug_lifetest_details25.htm) seem to have it.

I'm inclined to drop the exact version of the Dinse estimator, because the approximation seems to be more widespread (STATA and SAS only use the approximation).

2024-12-31 12:57 UTC, sebp commented on sksurv/datasets/base.py
> +        13. cgvh: Chronic GVHD: 1=Yes, 0=No
A [table](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#tables) might more suitable to describe the dataset. Headers could be "Index", "Name", "Description", "Encoding".

2024-12-31 12:57 UTC, sebp commented on sksurv/datasets/base.py
> +    The rest of the columns correspond to outcome variables:::
The line should end with "::" for a literal block.

2025-01-07 01:46 UTC, mvlvrd commented
Thanks for the review and sorry for the late response.
I have addressed most of the comments, please tell if you need more explanations or corrections.

I would like to keep the exact Dinse estimator, as it is the one I am using in production code.

2025-01-07 01:46 UTC, mvlvrd commented on sksurv/datasets/base.py
> +        13. cgvh: Chronic GVHD: 1=Yes, 0=No
Done

2025-01-07 01:46 UTC, mvlvrd commented on sksurv/datasets/base.py
> +    The dataset has 100 samples and 4 features:::
Done

2025-01-07 01:46 UTC, mvlvrd commented on sksurv/datasets/base.py
> +    The rest of the columns correspond to outcome variables:::
Done

2025-01-07 01:46 UTC, mvlvrd commented on sksurv/datasets/base.py
> +    either of the events: The endpoint (status) are therefore:
Done

2025-01-07 01:46 UTC, mvlvrd commented on sksurv/datasets/base.py
> +    .. [2] https://drive.google.com/file/d/1FPM264pE\_-F8DB7lvFeLB1yQ3HDo7c-i/view
Done

2025-01-07 01:46 UTC, mvlvrd commented on sksurv/nonparametric.py
> +    theta = z * np.multiply.outer(np.array([-1, 1]), theta)
`np.outer` flattens the input, (it is equivalent to `np.multiply.outer(a.ravel(), b.ravel())`) but I need to keep the dimensions of the input.
https://numpy.org/doc/2.1/reference/generated/numpy.outer.html

2025-01-07 01:47 UTC, mvlvrd commented on sksurv/nonparametric.py
> +    np.divide(sigma_t, den, where=den < -eps, out=theta)
I was just following the same conventions as in `_ci_logmlog`.

I have rewritten the whole function to be more explicit:
I removed the condition `ci[:, 1.0 - cum_inc <= eps] = 1.0`, and rewrote `ci[:, cum_inc <= eps] = 0.0` as `ci[:, zero_count] = 0.0`
The reason is that for zero counts the formula for the CI is not well defined. It still gets set to (0, 0) which is not great, but I don't know of a better solution for this particular case. (I could try to think about it if needed).

2025-01-07 01:47 UTC, mvlvrd commented on sksurv/nonparametric.py
> +    ci[:, 1.0 - cum_inc <= eps] = 1.0
See above comment.
The CI is an exponential, so with the current iteration it cannot be negative. Now it doesn't suppress the bug case of it being larger than one.

2025-01-07 01:47 UTC, mvlvrd commented on sksurv/nonparametric.py
> +    if conf_type not in {"log-log"}:
I decide to keep it this way to be consistent with the `_km_ci_estimator`. I can change it it you prefer it so.

2025-01-07 01:47 UTC, mvlvrd commented on sksurv/nonparametric.py
> +    var_type=None,
Done

2025-01-07 01:48 UTC, mvlvrd commented on sksurv/nonparametric.py
> +    var_a = np.einsum("rjk,jk,k->rj", irt**2, mask, dr / (n_at_risk * (n_at_risk - dr)))
I have rewritten all but one `einsum` to regular `sum`. I couldn't find a way to make it simpler without explicit loops or weird transpositions of the indices.

2025-01-07 21:36 UTC, sebp requested changes
Thanks for changing the use of `einsum`. My idea was to avoid the multiplication with `mask`, but I now understand that this isn't possible with `np.cumsum`. Using `np.sum` makes it a little bit easier to understand, but it might be worth it. Using `np.einsum` should be faster due to avoiding intermediate arrays.

I would revert to using `np.einsum` and leave the `np.sum` as a comment to explain what is being computed.

2025-01-07 21:36 UTC, sebp commented on sksurv/nonparametric.py
> +    k_idx = np.arange(n_t)[None, None, :]
Using a single instance of `np.arange(n_t)` should be sufficient.

2025-01-07 21:36 UTC, sebp commented on sksurv/nonparametric.py
> +    zero_count = cum_inc <= eps
`~zero_count` is used twice. Can you define `cum_inc > eps` and negate the result only ones when setting the values to 0?

2025-01-07 21:45 UTC, sebp commented on sksurv/nonparametric.py
> +    np.divide(sigma_t, den, where=den < -eps, out=theta)
I 'm getting confused by my own code I guess 🤦

Can we merge `_cr_ci_logmlog()` and `_ci_logmlog()` into a single function then?

2025-01-07 21:51 UTC, sebp commented on sksurv/nonparametric.py
> +    ci[:, 1.0 - cum_inc <= eps] = 1.0
I apologize, since `cum_inc` is a probability, it is valid.

2025-01-09 07:00 UTC, mvlvrd commented on sksurv/nonparametric.py
> +    zero_count = cum_inc <= eps
Done.

2025-01-09 07:00 UTC, mvlvrd commented on sksurv/datasets/base.py
> +    |       |            |                                              | | MDS=myelodysplastic syndrome            |
Sorry, I missed this. It looks like the actual data set is a subsample of the full data set:"In this book only the subgroup of 100 patients treated at the Princess Margaret Hospital are included." (Pintillie(s book Page 18)

I have removed the reference and added some comments.

2025-01-09 07:00 UTC, mvlvrd commented on sksurv/nonparametric.py
> +    np.divide(sigma_t, den, where=den < -eps, out=theta)
Thanks. I didn't notice the formulas for both cases are actually equivalent. I merged them accordingly.

2025-01-11 12:23 UTC, sebp commented on sksurv/nonparametric.py
> +    sigma_t is the square root of the estimator of the log of the variance of s.
Isn't `sigma_t` the standard deviation, instead of $\sqrt{log(\widehat{\mathrm{Var}})}$?

2025-01-11 15:00 UTC, mvlvrd commented on sksurv/nonparametric.py
> +    sigma_t is the square root of the estimator of the log of the variance of s.
I'm sorry, it is a mistake from my side. It should be `the variance of the log of s` instead of `the log of the variance of s`.

sigma_t is $\sqrt{\hat{Var}(\log{(s)})}$ because of the log-log transformation. If $\sigma =  \sqrt{\hat{Var}(s)}$ we would have to use $\exp(\sigma/(s*\log(s)))$ instead of $\exp(\sigma/log(s))$ for the CI.

2025-01-12 20:55 UTC, sebp approved these changes

2025-01-12 21:15 UTC, merged

2025-01-12 21:16 UTC, sebp commented
@mvlvrd Thanks for your hard work 🙏